
import "./globals.css";
import AuthProvider from "../components/context/AuthProvider";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`antialiased`}>{children}</body>
      </AuthProvider>
    </html>
  );
}
